export class PublikacjaModel {
  constructor(public _id: string,
              public rodzajPublikacji: string,
              public autorzyWewnetrzniId: string[],
              public autorzyZewnetrzni: string[],
              public redaktorzyWewnetrzniId: string[],
              public redaktorzyZewnetrzni: string[],
              public tytulPublikacji: string,
              public rokPublikacji: number,
              public jezykPublikacji: string,
              public tytulCzasopisma: string,
              public zeszyt: string,
              public strony: string,
              public tytulRozdzialu: string,
              public ISSN: string,
              public ISBN: string,
              public wydawnictwo: string,
              public DOI: string,
              public punkty: number) {}
}
